// Movie action types.
export const TRY_TO_FETCH_MOVIES = "TRY_TO_FETCH_MOVIES";
export const SUCCESSFULLY_FETCHED_MOVIES = "SUCCESSFULLY_FETCHED_MOVIES";
export const FAILED_TO_FETCH_MOVIES = "FAILED_TO_FETCH_MOVIES";

export const TRY_TO_FETCH_MOVIE_BY_ID = "TRY_TO_FETCH_MOVIE_BY_ID";
export const SUCCESSFULLY_FETCHED_MOVIE_BY_ID =
  "SUCCESSFULLY_FETCHED_MOVIE_BY_ID";
export const FAILED_TO_FETCH_MOVIE_BY_ID = "FAILED_TO_FETCH_MOVIE_BY_ID";

export const TRY_TO_ADD_A_MOVIE = "TRY_TO_ADD_A_MOVIE";
export const SUCCESSFULLY_ADDED_THE_MOVIE = "SUCCESSFULLY_ADDED_THE_MOVIE";
export const FAILED_TO_ADD_THE_MOVIE = "FAILED_TO_ADD_THE_MOVIE";

export const TRY_TO_DELETE_A_MOVIE = "TRY_TO_DELETE_A_MOVIE";
export const SUCCESSFULLY_DELETED_THE_MOVIE = "SUCCESSFULLY_DELETED_THE_MOVIE";
export const FAILED_TO_DELETE_THE_MOVIE = "FAILED_TO_DELETE_THE_MOVIE";

// Auth action types.
export const TRY_TO_SIGN_IN = "TRY_TO_SIGN_IN";
export const SUCCESSFULLY_SIGNED_IN = "SUCCESSFULLY_SIGNED_IN";
export const FAILED_TO_SIGN_IN = "FAILED_TO_SIGN_IN";

export const TRY_TO_SIGN_OUT = "TRY_TO_SIGN_OUT";
export const SUCCESSFULLY_SIGNED_OUT = "SUCCESSFULLY_SIGNED_OUT";
export const FAILED_TO_SIGN_OUT = "FAILED_TO_SIGN_OUT";

export const TRY_TO_CREATE_ACCOUNT = "TRY_TO_CREATE_ACCOUNT";
export const SUCCESSFULLY_CREATED_ACCOUNT = "SUCCESSFULLY_CREATED_ACCOUNT";
export const FAILED_TO_CREATE_ACCOUNT = "FAILED_TO_CREATE_ACCOUNT";
